apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluent-bit
  namespace: fluentd-bit
spec:
  interval: 15m
  path: "./fluent-bit"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluent-bit