apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebeat-talos
  namespace: filebeat
spec:
  releaseName: filebeat-talos
  chart:
    repository: https://charts.elastic.co
    name: filebeat
    version: 7.16.2
  values:
    apiVersion: beat.k8s.elastic.co/v1beta1
    kind: Beat
    metadata:
      name: talos
    spec:
      type: filebeat
      version: 7.16.2
      elasticsearchRef:
        name: talos
      config:
        filebeat.inputs:
          - type: "udp"
            host: "127.0.0.1:514"
            processors:
              - decode_json_fields:
                  fields: ["message"]
                  target: ""
              - timestamp:
                  field: "talos-time"
                  layouts:
                    - "2006-01-02T15:04:05.999999999Z07:00"
              - drop_fields:
                  fields: ["message", "talos-time"]
              - rename:
                  fields:
                    - from: "msg"
                      to: "message"
      daemonSet:
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 100%
        podTemplate:
          spec:
            dnsPolicy: ClusterFirstWithHostNet
            hostNetwork: true
            securityContext:
              runAsUser: 0
            containers:
              - name: filebeat
                ports:
                  - protocol: UDP
                    containerPort: 514
                    hostPort: 514