apiVersion: v1
kind: Service
metadata:
  name: service-deployment
  namespace: default
spec:
  selector:
    app: myapp-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  externalIPs:
    - 192.17.2.101
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myapp-deployment
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: myapp-deployment
    template:
      metadata:
        labels:
          app: myapp-deployment
      spec:
        containers:
        - name: myapp-deployment
          image: ladphp/flux-example:1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
