apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: filebeat
  namespace: filebeat
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/LAD-PHP/flux-example