apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: filebeat
  namespace: filebeat
spec:
  interval: 15m
  path: "./filebeat"
  prune: true
  sourceRef:
    kind: GitRepository
    name: filebeat